apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: production-app
  namespace: app-namespace
spec:
  hostnames:
  - app.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: app
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: app
      port: 8080
      weight: 1
    filters:
    - requestMirror:
        backendRef:
          group: ""
          kind: Service
          name: httspy
          namespace: monitoring
          port: 8080
      type: RequestMirror
    matches:
    - path:
        type: PathPrefix
        value: /